language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: 
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('punkt')"
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script: 
  - pytest --cov=poetic/

after_success:
  - coveralls