language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: 
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('punkt')"
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: 
  - pytest --cov=poetic/

after_success:
  - coveralls