{% set name = "poetic-py" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8b94fced7673523092769db2ed948aa1ad2a10e3e2cdf05ad9e2e7ec5125b9c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --force-reinstall --no-deps -vv "

requirements:
  build:
    - python
    - setuptools
  host:
    - python
  run:
    - python >=3.6,<3.9
    - tensorflow >=2
    - gensim
    - nltk
    - numpy

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
    - pytest-mock
  imports:
    - poetic
    

about:
  home: https://github.com/kevin931/poetic
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A poetry predictor and toolkit.

extra:
  recipe-maintainers:
    - kevin931
